Repository prgrms-web-devcourse/Team-Moongsal-Travel.zip-BE, pull requests merged in 2023-02, with the labels that each got.

#4 Feature/#1
  build.gradle
  src/main/java/shop/zip/travel/domain/base/BaseImage.java
  src/main/java/shop/zip/travel/domain/base/BaseTimeEntity.java
  src/main/java/shop/zip/travel/domain/image/entity/Image.java
  src/main/java/shop/zip/travel/domain/member/entity/Member.java
  src/main/java/shop/zip/travel/domain/post/travelog/entity/SubTravelogue.java
  src/main/java/shop/zip/travel/domain/post/travelog/entity/Travelogue.java
  src/main/java/shop/zip/travel/domain/post/travelog/entity/type/Address.java
  src/main/java/shop/zip/travel/domain/post/travelog/entity/type/Cost.java
  src/main/java/shop/zip/travel/domain/post/travelog/entity/type/Country.java
  src/main/java/shop/zip/travel/domain/post/travelog/entity/type/Period.java
  src/main/java/shop/zip/travel/domain/post/travelog/entity/type/Thumbnail.java
  src/main/java/shop/zip/travel/domain/post/travelog/entity/type/Transportation.java
  src/main/java/shop/zip/travel/domain/post/travelog/exception/PostNotFoundException.java
  src/main/java/shop/zip/travel/global/error/ErrorCode.java
  src/main/java/shop/zip/travel/global/error/GlobalExceptionHandler.java
  src/main/java/shop/zip/travel/global/error/exception/CustomNotFoundException.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/shop/zip/travel/domain/travelog/entity/PeriodTest.java
  src/test/java/shop/zip/travel/domain/travelog/entity/TravelogueTest.java
Labels: 🐰백엔드, 🧑🏻‍💻 feat

#22 Feature/#1 refactor
  src/main/java/shop/zip/travel/domain/base/BaseImage.java
  src/main/java/shop/zip/travel/domain/image/entity/Image.java
  src/main/java/shop/zip/travel/domain/post/data/Country.java
  src/main/java/shop/zip/travel/domain/post/image/entity/TravelPhoto.java
  src/main/java/shop/zip/travel/domain/post/subTravelog/data/Address.java
  src/main/java/shop/zip/travel/domain/post/subTravelog/data/Transportation.java
  src/main/java/shop/zip/travel/domain/post/subTravelog/entity/SubTravelogue.java
  src/main/java/shop/zip/travel/domain/post/travelog/data/Cost.java
  src/main/java/shop/zip/travel/domain/post/travelog/data/Period.java
  src/main/java/shop/zip/travel/domain/post/travelog/entity/Travelogue.java
  src/main/java/shop/zip/travel/domain/post/travelog/entity/type/Thumbnail.java
  src/test/java/shop/zip/travel/domain/travelog/entity/PeriodTest.java
Labels: 🐰백엔드, 🚑 fix, ♻️ refactor

#10 Feature/#3
  src/main/java/shop/zip/travel/TravelApplication.java
  src/main/java/shop/zip/travel/domain/member/dto/request/MemberSignupRequest.java
  src/main/java/shop/zip/travel/domain/member/entity/Member.java
  src/main/java/shop/zip/travel/domain/member/repository/MemberRepository.java
  src/main/java/shop/zip/travel/domain/member/service/MemberService.java
  src/main/java/shop/zip/travel/presentation/member/MemberController.java
  src/test/java/shop/zip/travel/domain/member/entity/MemberTest.java
Labels: 리뷰 요청

#27 [Feature/#12] 이메일 인증 기능 구현
  build.gradle
  src/main/java/shop/zip/travel/domain/email/config/EmailConfig.java
  src/main/java/shop/zip/travel/domain/email/dto/request/CodeValidateReq.java
  src/main/java/shop/zip/travel/domain/email/dto/request/EmailValidateReq.java
  src/main/java/shop/zip/travel/domain/email/exception/EmailSendFailException.java
  src/main/java/shop/zip/travel/domain/email/service/EmailService.java
  src/main/java/shop/zip/travel/domain/member/dto/request/MemberSignupReq.java
  src/main/java/shop/zip/travel/domain/member/entity/Member.java
  src/main/java/shop/zip/travel/domain/member/exception/DuplicatedEmailException.java
  src/main/java/shop/zip/travel/domain/member/exception/DuplicatedNicknameException.java
  src/main/java/shop/zip/travel/domain/member/exception/NotVerifiedAuthorizationCodeException.java
  src/main/java/shop/zip/travel/domain/member/repository/MemberRepository.java
  src/main/java/shop/zip/travel/domain/member/service/MemberService.java
  src/main/java/shop/zip/travel/global/config/RedisConfig.java
  src/main/java/shop/zip/travel/global/error/ErrorCode.java
  src/main/java/shop/zip/travel/global/error/GlobalExceptionHandler.java
  src/main/java/shop/zip/travel/global/error/exception/DuplicatedException.java
  src/main/java/shop/zip/travel/global/error/exception/NotVerifiedCodeException.java
  src/main/java/shop/zip/travel/global/util/RedisUtil.java
  src/main/java/shop/zip/travel/presentation/email/EmailController.java
  src/main/java/shop/zip/travel/presentation/member/MemberController.java
  src/main/resources/application.yml
  src/test/java/shop/zip/travel/domain/member/entity/MemberTest.java
Labels: 리뷰 요청, 🧑🏻‍💻 feat, ♻️ refactor

#29 Feature/#25
  src/main/java/shop/zip/travel/domain/post/data/Country.java
  src/main/java/shop/zip/travel/domain/post/subTravelogue/dto/req/SubTravelogueCreateReq.java
  src/main/java/shop/zip/travel/domain/post/subTravelogue/dto/res/SubTravelogueCreateRes.java
  src/main/java/shop/zip/travel/domain/post/subTravelogue/service/SubTravelogueService.java
  src/main/java/shop/zip/travel/domain/post/travelogue/data/Period.java
  src/main/java/shop/zip/travel/domain/post/travelogue/dto/req/TravelogueCreateReq.java
  src/main/java/shop/zip/travel/domain/post/travelogue/entity/Travelogue.java
  src/main/java/shop/zip/travel/domain/post/travelogue/service/TravelogueService.java
  src/main/java/shop/zip/travel/presentation/subTravelogue/SubTravelogueController.java
  src/test/java/shop/zip/travel/domain/travelog/entity/PeriodTest.java
Labels: 🐰백엔드, 🧑🏻‍💻 feat

#30 Feature/#14
  src/main/java/shop/zip/travel/domain/post/image/dto/TravelPhotoCreateReq.java
  src/main/java/shop/zip/travel/domain/post/subTravelogue/dto/SubTravelogueDetailRes.java
  src/main/java/shop/zip/travel/domain/post/travelogue/dto/res/TravelogueDetailRes.java
  src/main/java/shop/zip/travel/domain/post/travelogue/repository/TravelogueRepository.java
  src/main/java/shop/zip/travel/domain/post/travelogue/service/TravelogueService.java
  src/main/java/shop/zip/travel/presentation/travelogue/TravelogueController.java
Labels: 🐰백엔드, 🧑🏻‍💻 feat

#31 Feature/#24 게시물 전체 조회 구현
  src/main/java/shop/zip/travel/domain/post/travelogue/dto/TravelogueSimple.java
  src/main/java/shop/zip/travel/domain/post/travelogue/dto/res/TravelogueCustomSlice.java
  src/main/java/shop/zip/travel/domain/post/travelogue/dto/res/TravelogueSimpleRes.java
  src/main/java/shop/zip/travel/domain/post/travelogue/repository/TravelogueRepository.java
  src/main/java/shop/zip/travel/domain/post/travelogue/service/TravelogueService.java
  src/main/java/shop/zip/travel/presentation/travelogue/TravelogueController.java
  src/test/java/shop/zip/travel/domain/post/travelogue/DummyGenerator.java
  src/test/java/shop/zip/travel/domain/post/travelogue/repository/TravelogueRepositoryTest.java
  src/test/java/shop/zip/travel/domain/post/travelogue/service/TravelogueServiceTest.java
  src/test/java/shop/zip/travel/presentation/travelogue/TravelogueControllerTest.java
Labels: 리뷰 요청, 🐰백엔드, 🧑🏻‍💻 feat, 💯 test

#40 자체 로그인 기능 구현
  build.gradle
  src/main/java/shop/zip/travel/domain/member/dto/request/MemberSigninReq.java
  src/main/java/shop/zip/travel/domain/member/dto/response/MemberSigninRes.java
  src/main/java/shop/zip/travel/domain/member/exception/EmailNotMatchException.java
  src/main/java/shop/zip/travel/domain/member/exception/PasswordNotMatchException.java
  src/main/java/shop/zip/travel/domain/member/repository/MemberRepository.java
  src/main/java/shop/zip/travel/domain/member/service/MemberService.java
  src/main/java/shop/zip/travel/global/config/SecurityConfig.java
  src/main/java/shop/zip/travel/global/error/ErrorCode.java
  src/main/java/shop/zip/travel/global/error/GlobalExceptionHandler.java
  src/main/java/shop/zip/travel/global/error/exception/NotMatchException.java
  src/main/java/shop/zip/travel/global/filter/JwtAuthenticationFilter.java
  src/main/java/shop/zip/travel/global/security/CustomUserDetailsService.java
  src/main/java/shop/zip/travel/global/security/JwtTokenProvider.java
  src/main/java/shop/zip/travel/global/security/UserPrincipal.java
  src/main/java/shop/zip/travel/presentation/member/MemberController.java
  src/main/resources/application.yml
Labels: 리뷰 요청, 🧑🏻‍💻 feat

#41 [Feature/#39] SubTravelogue 생성 테스트 코드 작성
  src/main/java/shop/zip/travel/domain/post/subTravelogue/entity/SubTravelogue.java
  src/main/java/shop/zip/travel/domain/post/travelogue/repository/TravelogueRepository.java
  src/main/java/shop/zip/travel/global/security/UserPrincipal.java
  src/main/java/shop/zip/travel/presentation/travelogue/TravelogueController.java
  src/test/java/shop/zip/travel/domain/post/fake/FakeSubTravelogue.java
  src/test/java/shop/zip/travel/domain/post/fake/FakeTravelogue.java
  src/test/java/shop/zip/travel/domain/post/subTravelogue/entity/SubTravelogueTest.java
  src/test/java/shop/zip/travel/domain/post/subTravelogue/service/SubTravelogueServiceTest.java
  src/test/java/shop/zip/travel/domain/post/travelogue/DummyGenerator.java
  src/test/java/shop/zip/travel/domain/post/travelogue/repository/TravelogueRepositoryTest.java
  src/test/java/shop/zip/travel/domain/post/travelogue/service/FakeTravelogue.java
  src/test/java/shop/zip/travel/domain/post/travelogue/service/TravelogueServiceTest.java
  src/test/java/shop/zip/travel/presentation/subTravelogue/SubTravelogueControllerTest.java
  src/test/java/shop/zip/travel/presentation/travelogue/TravelogueControllerTest.java
Labels: 리뷰 요청, 🐰백엔드, 💯 test

#34 🧑🏻‍💻feat : search 개발
  .github/workflows/gradle.yml
  src/main/java/shop/zip/travel/domain/email/exception/EmailSendFailException.java
  src/main/java/shop/zip/travel/domain/email/service/EmailService.java
  src/main/java/shop/zip/travel/domain/post/data/Country.java
  src/main/java/shop/zip/travel/domain/post/travelogue/dto/TravelogueSimple.java
  src/main/java/shop/zip/travel/domain/post/travelogue/dto/res/TravelogueSimpleRes.java
  src/main/java/shop/zip/travel/domain/post/travelogue/repository/TravelogueRepository.java
  src/main/java/shop/zip/travel/domain/post/travelogue/repository/impl/TravelogueRepositoryImpl.java
  src/main/resources/static/docs/index.html
  src/test/java/shop/zip/travel/domain/post/travelogue/DummyGenerator.java
  src/test/java/shop/zip/travel/domain/post/travelogue/repository/impl/TravelogueRepositoryImplTest.java
  src/test/java/shop/zip/travel/presentation/travelogue/TravelogueControllerTest.java
Labels: 🐰백엔드, 🧑🏻‍💻 feat
