Repository prgrms-web-devcourse/Team-Moongsal-Travel.zip-BE, pull requests merged in 2023-03, with the labels that each got.

#51 Feature/#43 AccessToken 재요청 API 구현
  src/main/java/shop/zip/travel/domain/email/service/EmailService.java
  src/main/java/shop/zip/travel/domain/member/dto/request/AccessTokenReissueReq.java
  src/main/java/shop/zip/travel/domain/member/dto/response/MemberSigninRes.java
  src/main/java/shop/zip/travel/domain/member/exception/InvalidAccessTokenException.java
  src/main/java/shop/zip/travel/domain/member/exception/InvalidRefreshTokenException.java
  src/main/java/shop/zip/travel/domain/member/service/MemberService.java
  src/main/java/shop/zip/travel/global/config/SecurityConfig.java
  src/main/java/shop/zip/travel/global/error/ErrorCode.java
  src/main/java/shop/zip/travel/global/error/GlobalExceptionHandler.java
  src/main/java/shop/zip/travel/global/error/exception/InvalidTokenException.java
  src/main/java/shop/zip/travel/global/error/exception/JsonNotParsingException.java
  src/main/java/shop/zip/travel/global/filter/JwtExceptionFilter.java
  src/main/java/shop/zip/travel/global/security/JwtTokenProvider.java
  src/main/java/shop/zip/travel/global/util/RedisUtil.java
  src/main/java/shop/zip/travel/presentation/member/MemberController.java
  src/main/resources/application.yml
  src/test/java/shop/zip/travel/presentation/subTravelogue/SubTravelogueControllerTest.java
  src/test/java/shop/zip/travel/presentation/travelogue/TravelogueControllerTest.java
Labels: 🐰백엔드, 🧑🏻‍💻 feat

#45 Feature/#36 마이페이지 프로필 정보 확인 api 개발
  src/main/java/shop/zip/travel/domain/member/dto/response/MemberInfoRes.java
  src/main/java/shop/zip/travel/domain/member/entity/Member.java
  src/main/java/shop/zip/travel/domain/member/repository/MemberRepository.java
  src/main/java/shop/zip/travel/domain/member/service/MemberMyPageService.java
  src/main/java/shop/zip/travel/domain/member/service/MemberService.java
  src/main/java/shop/zip/travel/presentation/member/MemberMyPageController.java
  src/test/java/shop/zip/travel/presentation/member/MemberMyPageControllerTest.java
Labels: 🐰백엔드, 🧑🏻‍💻 feat

#46 Feature/#37 마이페이지 Travelogue조회 api 개발
  src/main/java/shop/zip/travel/domain/member/exception/NotLoggedInException.java
  src/main/java/shop/zip/travel/domain/member/service/MemberMyPageService.java
  src/main/java/shop/zip/travel/domain/post/travelogue/repository/TravelogueRepository.java
  src/main/java/shop/zip/travel/domain/post/travelogue/service/TravelogueService.java
  src/main/java/shop/zip/travel/global/error/ErrorCode.java
  src/main/java/shop/zip/travel/global/error/exception/UnauthorizedException.java
  src/main/java/shop/zip/travel/presentation/member/MemberMyPageController.java
  src/main/java/shop/zip/travel/presentation/travelogue/TravelogueController.java
  src/test/java/shop/zip/travel/domain/post/travelogue/repository/TravelogueRepositoryTest.java
  src/test/java/shop/zip/travel/presentation/member/MemberMyPageControllerTest.java
Labels: 🐰백엔드, 🧑🏻‍💻 feat

#52 Feature/#47 마이페이지 프로필 변경 api 개발
  src/main/java/shop/zip/travel/domain/member/dto/request/MemberUpdateReq.java
  src/main/java/shop/zip/travel/domain/member/dto/response/MemberInfoRes.java
  src/main/java/shop/zip/travel/domain/member/entity/Member.java
  src/main/java/shop/zip/travel/domain/member/exception/NotLoggedInException.java
  src/main/java/shop/zip/travel/domain/member/service/MemberMyPageService.java
  src/main/java/shop/zip/travel/domain/member/service/MemberService.java
  src/main/java/shop/zip/travel/global/error/ErrorCode.java
  src/main/java/shop/zip/travel/global/error/exception/UnauthorizedException.java
  src/main/java/shop/zip/travel/presentation/member/MemberMyPageController.java
  src/test/java/shop/zip/travel/presentation/member/MemberMyPageControllerTest.java
Labels: 🐰백엔드, 🧑🏻‍💻 feat

#60 Feature/#50 북마크한 게시글 목록 조회 api 개발
  src/main/java/shop/zip/travel/domain/bookmark/entity/Bookmark.java
  src/main/java/shop/zip/travel/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/shop/zip/travel/domain/bookmark/repository/impl/BookmarkRepositoryImpl.java
  src/main/java/shop/zip/travel/domain/bookmark/repository/querydsl/BookmarkRepositoryQuerydsl.java
  src/main/java/shop/zip/travel/domain/bookmark/service/BookmarkService.java
  src/main/java/shop/zip/travel/domain/member/service/MemberMyPageService.java
  src/main/java/shop/zip/travel/domain/post/subTravelogue/service/SubTravelogueService.java
  src/main/java/shop/zip/travel/domain/post/travelogue/service/TravelogueService.java
  src/main/java/shop/zip/travel/presentation/bookmark/BookmarkController.java
  src/main/java/shop/zip/travel/presentation/config/jwt/service/JwtService.java
  src/main/java/shop/zip/travel/presentation/member/MemberMyPageController.java
  src/test/java/shop/zip/travel/domain/post/subTravelogue/service/SubTravelogueServiceTest.java
  src/test/java/shop/zip/travel/presentation/bookmark/BookmarkControllerTest.java
  src/test/java/shop/zip/travel/presentation/member/MemberMyPageControllerTest.java
  src/test/java/shop/zip/travel/presentation/subTravelogue/SubTravelogueControllerTest.java
Labels: 🐰백엔드, 🧑🏻‍💻 feat

#59 Feature/#58 북마크 기능 개발
  src/test/java/shop/zip/travel/presentation/bookmark/BookmarkControllerTest.java
Labels: 🐰백엔드, 🧑🏻‍💻 feat

#62 [Feature/#44] 임시저장 기능 구현
  src/docs/asciidoc/index.adoc
  src/main/java/shop/zip/travel/domain/post/data/Country.java
  src/main/java/shop/zip/travel/domain/post/data/DefaultValue.java
  src/main/java/shop/zip/travel/domain/post/data/TempCountry.java
  src/main/java/shop/zip/travel/domain/post/subTravelogue/data/Address.java
  src/main/java/shop/zip/travel/domain/post/subTravelogue/data/TempAddress.java
  src/main/java/shop/zip/travel/domain/post/subTravelogue/dto/req/SubTravelogueCreateReq.java
  src/main/java/shop/zip/travel/domain/post/subTravelogue/entity/SubTravelogue.java
  src/main/java/shop/zip/travel/domain/post/subTravelogue/service/SubTravelogueService.java
  src/main/java/shop/zip/travel/domain/post/travelogue/data/Cost.java
  src/main/java/shop/zip/travel/domain/post/travelogue/data/Period.java
  src/main/java/shop/zip/travel/domain/post/travelogue/data/temp/TempCost.java
  src/main/java/shop/zip/travel/domain/post/travelogue/data/temp/TempPeriod.java
  src/main/java/shop/zip/travel/domain/post/travelogue/dto/req/TravelogueCreateReq.java
  src/main/java/shop/zip/travel/domain/post/travelogue/dto/res/TravelogueCreateRes.java
  src/main/java/shop/zip/travel/domain/post/travelogue/dto/res/TraveloguePublishRes.java
  src/main/java/shop/zip/travel/domain/post/travelogue/entity/Travelogue.java
  src/main/java/shop/zip/travel/domain/post/travelogue/exception/InvalidPublishTravelogueException.java
  src/main/java/shop/zip/travel/domain/post/travelogue/repository/TravelogueRepository.java
  src/main/java/shop/zip/travel/domain/post/travelogue/service/TravelogueMyTempService.java
  src/main/java/shop/zip/travel/domain/post/travelogue/service/TraveloguePublishService.java
  src/main/java/shop/zip/travel/domain/post/travelogue/service/TravelogueService.java
  src/main/java/shop/zip/travel/global/error/ErrorCode.java
  src/main/java/shop/zip/travel/global/error/GlobalExceptionHandler.java
  src/main/java/shop/zip/travel/presentation/member/MemberMyPageController.java
  src/main/java/shop/zip/travel/presentation/subTravelogue/SubTravelogueController.java
  src/main/java/shop/zip/travel/presentation/travelogue/TravelogueController.java
  src/test/java/shop/zip/travel/domain/post/fake/FakeTravelogue.java
  src/test/java/shop/zip/travel/domain/post/subTravelogue/entity/SubTravelogueTest.java
  src/test/java/shop/zip/travel/domain/post/subTravelogue/service/SubTravelogueServiceTest.java
  src/test/java/shop/zip/travel/domain/post/travelogue/DummyGenerator.java
  src/test/java/shop/zip/travel/domain/post/travelogue/repository/TravelogueRepositoryTest.java
  src/test/java/shop/zip/travel/domain/post/travelogue/service/TravelogueMyTempServiceTest.java
  src/test/java/shop/zip/travel/domain/post/travelogue/service/TraveloguePublishServiceTest.java
  src/test/java/shop/zip/travel/domain/post/travelogue/service/TravelogueServiceTest.java
  src/test/java/shop/zip/travel/domain/travelog/entity/TravelogueTest.java
  src/test/java/shop/zip/travel/presentation/member/MemberMyPageControllerTest.java
  src/test/java/shop/zip/travel/presentation/subTravelogue/SubTravelogueControllerTest.java
  src/test/java/shop/zip/travel/presentation/travelogue/TravelogueControllerTest.java
Labels: 리뷰 요청, 🐰백엔드, 🧑🏻‍💻 feat

#65 Feature/#63 조회수 개발
  src/main/java/shop/zip/travel/domain/bookmark/repository/impl/BookmarkRepositoryImpl.java
  src/main/java/shop/zip/travel/domain/post/subTravelogue/dto/res/SubTravelogueDetailRes.java
  src/main/java/shop/zip/travel/domain/post/travelogue/dto/res/TravelogueDetailRes.java
  src/main/java/shop/zip/travel/domain/post/travelogue/entity/Travelogue.java
  src/main/java/shop/zip/travel/domain/post/travelogue/service/TravelogueService.java
  src/main/java/shop/zip/travel/domain/post/util/CookieUtil.java
  src/main/java/shop/zip/travel/presentation/travelogue/TravelogueController.java
  src/test/java/shop/zip/travel/domain/post/travelogue/data/PeriodTest.java
  src/test/java/shop/zip/travel/domain/post/travelogue/data/TravelogueTest.java
  src/test/java/shop/zip/travel/domain/post/travelogue/service/TravelogueServiceTest.java
  src/test/java/shop/zip/travel/presentation/travelogue/TravelogueControllerTest.java
Labels: 🐰백엔드, 🧑🏻‍💻 feat

#76 Feature/#67 검색 및 필터링 기능 구현
  src/docs/asciidoc/index.adoc
  src/main/java/shop/zip/travel/domain/post/travelogue/dto/TravelogueSearchFilter.java
  src/main/java/shop/zip/travel/domain/post/travelogue/repository/impl/TravelogueRepositoryImpl.java
  src/main/java/shop/zip/travel/domain/post/travelogue/repository/querydsl/TravelogueRepositoryQuerydsl.java
  src/main/java/shop/zip/travel/domain/post/travelogue/service/TravelogueService.java
  src/main/java/shop/zip/travel/presentation/travelogue/TravelogueController.java
  src/test/java/shop/zip/travel/domain/post/travelogue/DummyGenerator.java
  src/test/java/shop/zip/travel/domain/post/travelogue/service/TravelogueServiceTest.java
  src/test/java/shop/zip/travel/presentation/travelogue/TravelogueControllerTest.java
Labels: 🐰백엔드, 🧑🏻‍💻 feat

#71 [Feature/#64] 좋아요 기능 구현
  src/main/java/shop/zip/travel/domain/bookmark/repository/impl/BookmarkRepositoryImpl.java
  src/main/java/shop/zip/travel/domain/post/travelogue/dto/TravelogueSimple.java
  src/main/java/shop/zip/travel/domain/post/travelogue/dto/res/TravelogueDetailRes.java
  src/main/java/shop/zip/travel/domain/post/travelogue/dto/res/TravelogueSimpleRes.java
  src/main/java/shop/zip/travel/domain/post/travelogue/entity/Like.java
  src/main/java/shop/zip/travel/domain/post/travelogue/entity/Travelogue.java
  src/main/java/shop/zip/travel/domain/post/travelogue/exception/NoAuthorizationException.java
  src/main/java/shop/zip/travel/domain/post/travelogue/repository/TravelogueLikeRepository.java
  src/main/java/shop/zip/travel/domain/post/travelogue/repository/TravelogueRepository.java
  src/main/java/shop/zip/travel/domain/post/travelogue/repository/impl/TravelogueRepositoryImpl.java
  src/main/java/shop/zip/travel/domain/post/travelogue/repository/querydsl/TravelogueRepositoryQuerydsl.java
  src/main/java/shop/zip/travel/domain/post/travelogue/service/TravelogueLikeService.java
  src/main/java/shop/zip/travel/domain/post/travelogue/service/TraveloguePublishService.java
  src/main/java/shop/zip/travel/domain/post/travelogue/service/TravelogueService.java
  src/main/java/shop/zip/travel/global/error/ErrorCode.java
  src/main/java/shop/zip/travel/global/error/GlobalExceptionHandler.java
  src/main/java/shop/zip/travel/presentation/travelogue/TravelogueController.java
  src/main/java/shop/zip/travel/presentation/travelogue/TravelogueLikeController.java
  src/test/java/shop/zip/travel/domain/post/travelogue/DummyGenerator.java
  src/test/java/shop/zip/travel/domain/post/travelogue/entity/LikeTest.java
  src/test/java/shop/zip/travel/domain/post/travelogue/service/TravelogueLikeServiceTest.java
  src/test/java/shop/zip/travel/domain/post/travelogue/service/TraveloguePublishServiceTest.java
  src/test/java/shop/zip/travel/domain/post/travelogue/service/TravelogueServiceTest.java
  src/test/java/shop/zip/travel/presentation/member/MemberMyPageControllerTest.java
  src/test/java/shop/zip/travel/presentation/travelogue/TravelogueControllerTest.java
  src/test/java/shop/zip/travel/presentation/travelogue/TravelogueLikeControllerTest.java
Labels: 🐰백엔드, 🧑🏻‍💻 feat

#69 Feature/#68 게시글 상세조회시 북마크 여부확인 필드 추가
  src/main/java/shop/zip/travel/domain/bookmark/repository/impl/BookmarkRepositoryImpl.java
  src/main/java/shop/zip/travel/domain/bookmark/repository/querydsl/BookmarkRepositoryQuerydsl.java
  src/main/java/shop/zip/travel/domain/post/travelogue/dto/res/TravelogueDetailRes.java
  src/main/java/shop/zip/travel/domain/post/travelogue/service/TravelogueService.java
  src/main/java/shop/zip/travel/presentation/travelogue/TravelogueController.java
  src/test/java/shop/zip/travel/domain/post/travelogue/service/TravelogueServiceTest.java
  src/test/java/shop/zip/travel/presentation/travelogue/TravelogueControllerTest.java
Labels: 🐰백엔드, 🧑🏻‍💻 feat

#79 Feature/#38 OAuth2 개발
  src/main/java/shop/zip/travel/domain/member/entity/Member.java
  src/main/java/shop/zip/travel/domain/member/entity/Provider.java
  src/main/java/shop/zip/travel/global/config/SecurityConfig.java
  src/main/java/shop/zip/travel/global/oauth/CustomOAuth2UserService.java
  src/main/java/shop/zip/travel/global/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/shop/zip/travel/global/oauth/dto/OAuth2Attribute.java
  src/main/java/shop/zip/travel/global/oauth/dto/OAuthAttributes.java
  src/main/java/shop/zip/travel/global/security/UserPrincipal.java
Labels: 🦊프론트, 🧑🏻‍💻 feat

#75 [feature/#66]스크랩 생성, 조회, 삭제 API 생성
  .gitignore
  build.gradle
  src/main/java/shop/zip/travel/domain/storage/document/Place.java
  src/main/java/shop/zip/travel/domain/storage/document/Storage.java
  src/main/java/shop/zip/travel/domain/storage/dto/req/ScrapCreateReq.java
  src/main/java/shop/zip/travel/domain/storage/dto/req/StorageCreateReq.java
  src/main/java/shop/zip/travel/domain/storage/dto/res/ScrapDetailRes.java
  src/main/java/shop/zip/travel/domain/storage/dto/res/ScrapListRes.java
  src/main/java/shop/zip/travel/domain/storage/dto/res/ScrapSimpleRes.java
  src/main/java/shop/zip/travel/domain/storage/exception/StorageNotFoundException.java
  src/main/java/shop/zip/travel/domain/storage/repository/StorageRepository.java
  src/main/java/shop/zip/travel/domain/storage/service/StorageService.java
  src/main/java/shop/zip/travel/global/error/ErrorCode.java
  src/main/java/shop/zip/travel/presentation/scrap/StorageController.java
  src/main/resources/static/docs/rest-docs.html
  src/test/java/shop/zip/travel/presentation/scrap/StorageControllerTest.java
Labels: 리뷰 요청, 🐰백엔드

#88 Feature/#83 북마크 목록 조회시 리턴타입 변경
  src/main/java/shop/zip/travel/domain/bookmark/repository/impl/BookmarkRepositoryImpl.java
  src/main/java/shop/zip/travel/domain/bookmark/repository/querydsl/BookmarkRepositoryQuerydsl.java
  src/main/java/shop/zip/travel/domain/member/service/MemberMyPageService.java
  src/main/java/shop/zip/travel/presentation/member/MemberMyPageController.java
  src/test/java/shop/zip/travel/presentation/member/MemberMyPageControllerTest.java
Labels: 🐰백엔드, ♻️ refactor

#89 Feature/#84 마이페이지 travelogue조회시 리턴타입 변경
  src/main/java/shop/zip/travel/domain/member/service/MemberMyTravelogueService.java
  src/main/java/shop/zip/travel/domain/post/travelogue/repository/TravelogueRepository.java
  src/test/java/shop/zip/travel/presentation/member/MemberMyTravelogueControllerTest.java
Labels: 🐰백엔드, ♻️ refactor

#100 [#99] DateTime 리턴 포맷 변경
  src/main/java/shop/zip/travel/domain/post/travelogue/dto/res/PeriodDetailForUpdateRes.java
  src/main/java/shop/zip/travel/domain/post/travelogue/dto/res/TravelogueDetailForUpdateRes.java
Labels: 🐰백엔드, ♻️ refactor

#101 💯test: REST docs 관련 코드 수정
  src/test/java/shop/zip/travel/presentation/member/MemberMyTravelogueControllerTest.java
Labels: 🐰백엔드, ♻️ refactor

#106 Hotfix/#1/deploy change
  .github/workflows/build.yml
  .github/workflows/codeDeploy.yml
  src/main/resources/static/docs/rest-docs.html
  src/test/java/shop/zip/travel/presentation/travelogue/TravelogueControllerTest.java
Labels: 🔨 chore

#103 [Feature/#102] 게시글 상세조회에 작성자 판단 여부 필드 추가
  src/main/java/shop/zip/travel/domain/post/subTravelogue/dto/res/SubTravelogueDetailRes.java
  src/main/java/shop/zip/travel/domain/post/travelogue/dto/res/TravelogueDetailRes.java
  src/main/java/shop/zip/travel/domain/post/travelogue/service/TravelogueService.java
  src/test/java/shop/zip/travel/domain/post/travelogue/service/TravelogueServiceTest.java
  src/test/java/shop/zip/travel/presentation/member/MemberMyTravelogueControllerTest.java
  src/test/java/shop/zip/travel/presentation/travelogue/TravelogueControllerTest.java
Labels: 🐰백엔드, 🚑 fix, ♻️ refactor

#95 Feature/#92 코드 포맷팅 변경
  src/main/java/shop/zip/travel/domain/bookmark/entity/Bookmark.java
  src/main/java/shop/zip/travel/domain/bookmark/repository/impl/BookmarkRepositoryImpl.java
  src/main/java/shop/zip/travel/domain/bookmark/service/BookmarkService.java
  src/main/java/shop/zip/travel/domain/member/service/MemberMyPageService.java
  src/main/java/shop/zip/travel/domain/post/travelogue/repository/impl/TravelogueRepositoryImpl.java
  src/main/java/shop/zip/travel/presentation/bookmark/BookmarkController.java
  src/main/java/shop/zip/travel/presentation/travelogue/TravelogueController.java
Labels: 🐰백엔드, ♻️ refactor

#96 Feature/#85 검색기능 유효성 검사
  src/main/java/shop/zip/travel/domain/post/travelogue/dto/TravelogueSearchFilter.java
  src/main/java/shop/zip/travel/global/error/GlobalExceptionHandler.java
  src/test/java/shop/zip/travel/domain/post/travelogue/dto/TravelogueSearchFilterTest.java
  src/test/java/shop/zip/travel/presentation/travelogue/TravelogueControllerTest.java
Labels: 🐰백엔드, 🧑🏻‍💻 feat

#108 Feature/#107 마이페이지 및 북마크 service 테스트 코드 추가
  src/test/java/shop/zip/travel/domain/bookmark/service/BookmarkServiceTest.java
  src/test/java/shop/zip/travel/domain/member/service/MemberMyPageServiceTest.java
Labels: 🐰백엔드, 💯 test

#111 [hotfix/#3] 기본으로 최신순으로 조회되도록 수정 및 조회수순으로 조회되도록 추가
  bin/main/static/docs/rest-docs.html
  bin/main/static/kakao.html
  src/main/java/shop/zip/travel/domain/post/travelogue/repository/TravelogueRepository.java
  src/main/java/shop/zip/travel/domain/post/travelogue/service/TravelogueService.java
  src/main/java/shop/zip/travel/presentation/travelogue/TravelogueController.java
Labels: 🐰백엔드, 🚑 fix, ♻️ refactor
